### PR TITLE
Featured collections

### PR DESCRIPTION
**Pull request by lilyfielding**
Hey Laura! Here's what I've been up to today:

### Webpack Config

- As you know, I've been having a lot of issues with webpack deleting files from the `dist` directory. At first, the issue seemed to be fixed by running `yarn build-dev` and then `theme deploy`, however I realised today that the problem was being caused by `yarn watch`.
- I figured the issue must be with `webpack --watch`, so I went into the config file and reverted the changes you made to the `output` path and filename. This has fixed the issue of the files deleting unnecessarily.
- I haven't tested to see whether the issue of old files *not* deleting has returned now that I've changed the config, so this is something to watch out for.

### Featured Collections Section

- Added liquid markup and responsive styles
- The schema structure for this section is a lil bit different to how I'd normally do it. If this section were just appearing on the homepage, I'd give the user the ability to add each collection as a `block`. Since this section will repeat on the Search and 404 pages, and Shopify doesn't allow section blocks unless it's an index section, I've instead added the collection pickers inside `section.settings`. This means that we should be able to include the same section file on each page without needing to modify the schema. 
- Added helper classes to achieve the two-column grid layout of the section, falling back to one column on mobile.
- I also quickly added collections for Men and Women on the Shopify backend.

### Image With Text Section

- After I'd styled Featured Collections, it occurred to me that I could use the same grid helpers to style Image With Text, so I've refactored the code with these styles.
- TIL that you can reverse the direction of CSS grid using `direction: rtl`! I've included this in a `grid-reverse` helper class.

### CODE REVIEW

**Comment by 1aurabrown** [comment]
Regarding webpack, the change I made was to address the previous issue of deleted liquid files sticking around in the dist/folder. There is a webpack plugin that will delete the contents of the build folder before each build, which in theory is a good idea so that deleted source files don't remain in the build directory. However it seems like that when the build directory gets cleaned, this gets pushed to Shopify, but then the subsequent result of the complete build resulting from `webpack --watch` doesn't get pushed. Maybe we can add a separate command to clean the dist/folder first without using the webpack plugin.

**Comment by quintinradford** [comment]
That makes sense. How do we add a separate command, @1aurabrown? I am very much a webpack novice.

**Comment by 1aurabrown** [comment]
i can try setting this up and show you
-- 
Laura Brown
laurabrown.xyz

**Comment by lilyfielding** [comment]
Would the clean command be something like this?

`"clean": "rm -rf ./dist/assets/theme.js && rm -rf ./dist/assets/theme.css && rm -rf ./dist/sections/*.liquid && rm -rf ./dist/snippets/*.liquid"`

Then we run `yarn start` afterwards to push the files to Shopify again

**Comment by lilyfielding** [comment]
@1aurabrown am I okay to merge this? There's a couple of conflicts with the latest PRs but I can sort through them manually

**Comment by 1aurabrown** [comment]
should be meregeable! :)
-- 
Laura Brown
laurabrown.xyz

**Pull request merged**
